const script = document.createElement("script");
script.src = "https://widget.kapa.ai/kapa-widget.bundle.js";
script.async = true;
script.setAttribute("data-website-id", "5b21ac2d-dd52-41f2-b02b-cd82467e45cc");
script.setAttribute("data-project-name", "RunPod");
script.setAttribute("data-project-color", "#070D27");
script.setAttribute("data-project-logo", "https://raw.githubusercontent.com/runpod/docs/refs/heads/mintlify-migration/icon_square.svg",);
script.setAttribute("data-button-image-width", 30);
script.setAttribute("data-button-image-height", 30);
document.head.appendChild(script);