module.exports = {
  // Sidebar for "Get Started"
  docsSidebar: [
    {
      type: "doc",
      id: "overview",
    },
    {
      type: "category",
      label: "Get started",
      items: [
        {
          type: "autogenerated",
          dirName: "get-started",
        },
      ],
    },
    {
      type: "category",
      label: "Serverless",
      link: {
        type: "doc",
        id: "serverless/index",
      },
      items: [
        {
          type: "category",
          label: "Quick start",
          items: [
            {
              type: "doc",
              id: "serverless/quick-start/deploy-models",
              label: "Deploy popular models"
            },
            {
              type: "doc",
              id: "serverless/github-integration",
              label: "GitHub integration"
            },
            {
              type: "doc",
              id: "serverless/quick-deploys",
              label: "Quick deploys"
            },
            {
              type: "doc",
              id: "serverless/overview",
              label: "Concepts overview"
            }
          ]
        },
        {
          type: "category",
          label: "Build custom",
          items: [
            {
              type: "doc",
              id: "serverless/build/first-endpoint",
              label: "Create your first endpoint"
            },
            {
              type: "doc",
              id: "serverless/get-started",
              label: "Step-by-step guide"
            },
            {
              type: "doc",
              id: "serverless/workers/overview",
              label: "Worker overview"
            }
          ]
        },
        {
          type: "category",
          label: "Manage & optimize",
          items: [
            {
              type: "doc",
              id: "serverless/manage/scaling",
              label: "Configure autoscaling"
            },
            {
              type: "category",
              label: "Endpoint management",
              items: [
                {
                  type: "doc",
                  id: "serverless/endpoints/overview",
                  label: "Endpoints overview"
                },
                {
                  type: "doc",
                  id: "serverless/endpoints/get-started",
                  label: "Get started with endpoints"
                },
                {
                  type: "doc",
                  id: "serverless/endpoints/send-requests",
                  label: "Send requests"
                },
                {
                  type: "doc",
                  id: "serverless/endpoints/job-operations",
                  label: "Job operations"
                },
                {
                  type: "doc",
                  id: "serverless/endpoints/manage-endpoints",
                  label: "Manage endpoints"
                }
              ]
            }
          ]
        },
        {
          type: "category",
          label: "Use cases & examples",
          items: [
            {
              type: "doc",
              id: "serverless/examples/text-generation",
              label: "Text generation"
            }
          ]
        },
        {
          type: "category",
          label: "Reference",
          items: [
            {
              type: "doc",
              id: "serverless/reference/configurations",
              label: "Configuration options"
            },
            {
              type: "doc",
              id: "serverless/reference/troubleshooting",
              label: "Troubleshooting guide"
            },
            {
              type: "doc",
              id: "serverless/references/endpoint-configurations",
              label: "Endpoint configurations"
            },
            {
              type: "doc",
              id: "serverless/references/job-states",
              label: "Job states"
            },
            {
              type: "doc",
              id: "serverless/references/operations",
              label: "API operations"
            }
          ]
        }
      ],
    },
    {
      type: "category",
      label: "Workers",
      items: [
        {
          type: "doc",
          id: "serverless/workers/overview",
          label: "Overview"
        },
        {
          type: "category",
          label: "Handler functions",
          items: [
            {
              type: "autogenerated",
              dirName: "serverless/workers/handlers",
            }
          ]
        },
        {
          type: "category",
          label: "Development",
          items: [
            {
              type: "autogenerated",
              dirName: "serverless/workers/development",
            }
          ]
        },
        {
          type: "category",
          label: "Deployment",
          items: [
            {
              type: "autogenerated",
              dirName: "serverless/workers/deploy",
            }
          ]
        },
        {
          type: "category",
          label: "vLLM workers",
          items: [
            {
              type: "doc",
              id: "serverless/workers/vllm/overview",
              label: "Overview"
            },
            {
              type: "doc",
              id: "serverless/workers/vllm/get-started",
              label: "Get started"
            },
            {
              type: "doc",
              id: "serverless/workers/vllm/openai-compatibility",
              label: "OpenAI compatibility"
            },
            {
              type: "doc",
              id: "serverless/workers/vllm/configurable-endpoints",
              label: "Configurable endpoints"
            },
            {
              type: "doc",
              id: "serverless/workers/vllm/environment-variables",
              label: "Environment variables"
            }
          ]
        },
        {
          type: "category",
          label: "Specialized workers",
          items: [
            {
              type: "doc",
              id: "serverless/workers/specialized/stable-diffusion",
              label: "Stable Diffusion"
            },
            {
              type: "doc",
              id: "serverless/workers/specialized/tts",
              label: "Text-to-Speech"
            }
          ]
        }
      ]
    },
    {
      type: "category",
      label: "Pods",
      items: [
        {
          type: "autogenerated",
          dirName: "pods",
        },
      ],
    },
    {
      type: "category",
      label: "runpodctl",
      items: [
        {
          type: "autogenerated",
          dirName: "runpodctl",
        },
      ],
    },
    {
      type: "doc",
      id: "fine-tune/index",
      label: "Fine-tune a model",
    },
    {
      type: "doc",
      id: "instant-clusters/index",
      label: "Instant Clusters",
    },
    {
      type: "category",
      label: "SDKs",
      items: [
        {
          type: "autogenerated",
          dirName: "sdks",
        },
      ],
    },
    {
      type: "category",
      label: "Integrations",
      link: {
        type: "doc",
        id: "integrations/overview",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "integrations/dstack",
        },
        {
          type: "autogenerated",
          dirName: "integrations/mods",
        },
        {
          type: "autogenerated",
          dirName: "integrations/skypilot",
        },
      ],
    },
    {
      type: "category",
      label: "Hosting",
      items: [
        {
          type: "autogenerated",
          dirName: "hosting",
        },
      ],
    },
    {
      type: "category",
      label: "References",
      items: [
        {
          type: "autogenerated",
          dirName: "references",
        },
        {
          type: "link",
          label: "GraphQL Spec",
          href: "https://graphql-spec.runpod.io",
        },
      ],
    },
    {
      type: "doc",
      id: "glossary",
    },
  ],

  // Sidebar for "Tutorials"
  tutorialsSidebar: [
    {
      type: "doc",
      id: "tutorials/overview",
    },
    {
      type: "category",
      label: "Introduction",
      items: [
        {
          type: "autogenerated",
          dirName: "tutorials/introduction",
        },
      ],
    },
    {
      type: "category",
      label: "Serverless",
      items: [
        {
          type: "autogenerated",
          dirName: "tutorials/serverless",
        },
      ],
    },
    {
      type: "category",
      label: "Workers",
      items: [
        {
          type: "doc",
          id: "tutorials/workers/overview",
          label: "Overview"
        },
        {
          type: "doc",
          id: "tutorials/workers/vllm-worker",
          label: "Create a vLLM worker"
        },
        {
          type: "doc",
          id: "tutorials/workers/custom-worker",
          label: "Build a custom worker"
        }
      ],
    },
    {
      type: "category",
      label: "Pods",
      items: [
        {
          type: "autogenerated",
          dirName: "tutorials/pods",
        },
      ],
    },
    {
      type: "category",
      label: "SDKs",
      items: [
        {
          type: "autogenerated",
          dirName: "tutorials/sdks",
        },
      ],
    },
    {
      type: "category",
      label: "Migrations",
      items: [
        {
          type: "autogenerated",
          dirName: "tutorials/migrations",
        },
      ],
    },
  ],
};
