module.exports = {
  // Sidebar for "Get Started"
  docsSidebar: [
    {
      type: "doc",
      id: "overview",
    },
    {
      type: "category",
      label: "Get started",
      items: [
        {
          type: "autogenerated",
          dirName: "get-started",
        },
      ],
    },
    {
      type: "category",
      label: "Pods",
      items: [
        {
          type: "autogenerated",
          dirName: "pods",
        },
      ],
    },
    {
      type: "category",
      label: "Serverless",
      items: [
        {
          type: "autogenerated",
          dirName: "serverless",
        },
      ],
    },
    {
      type: "doc",
      id: "ai-apis",
    },
    {
      type: "category",
      label: "GraphQL",
      items: [
        {
          type: "autogenerated",
          dirName: "graphql",
        },
      ],
    },
    {
      type: "category",
      label: "Hosting",
      items: [
        {
          type: "autogenerated",
          dirName: "hosting",
        },
      ],
    },
    {
      type: "category",
      label: "References",
      items: [
        {
          type: "autogenerated",
          dirName: "references",
        },
      ],
    },
    {
      type: "doc",
      id: "glossary",
    },
  ],

  // Sidebar for "Tutorials"
  tutorialsSidebar: [
    {
      type: "category",
      label: "Introduction",
      items: [
        {
          type: "autogenerated",
          dirName: "tutorials/introduction",
        },
      ],
    },
    {
      type: "category",
      label: "Pods",
      items: [
        {
          type: "autogenerated",
          dirName: "tutorials/pods",
        },
      ],
    },
    {
      type: "category",
      label: "Serverless",
      items: [
        {
          type: "autogenerated",
          dirName: "tutorials/serverless",
        },
      ],
    },
    {
      type: "category",
      label: "AI APIs",
      items: [
        {
          type: "autogenerated",
          dirName: "tutorials/ai-apis",
        },
      ],
    },
  ],
};
